
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {
    public int z=0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        addbuyerbtn.setVisible(false);
        updatebuyerbtn.setVisible(false);
        buydetbtn.setVisible(false);
        delbuybtn.setVisible(false);
        addprobtn.setVisible(false);
        updprobtn.setVisible(false);
        prodetbtn.setVisible(false);
        delprobtn.setVisible(false);
        billbtn.setVisible(false);
        btnlogout.setVisible(false);
        btnclose.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel8.setVisible(false);
         jLabel9.setVisible(false);
         jLabel10.setVisible(false);
         jLabel11.setVisible(false);
         jLabel12.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showbtn = new javax.swing.JButton();
        addbuyerbtn = new javax.swing.JButton();
        updatebuyerbtn = new javax.swing.JButton();
        buydetbtn = new javax.swing.JButton();
        delbuybtn = new javax.swing.JButton();
        addprobtn = new javax.swing.JButton();
        updprobtn = new javax.swing.JButton();
        prodetbtn = new javax.swing.JButton();
        delprobtn = new javax.swing.JButton();
        billbtn = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(70, 70));
        setMinimumSize(new java.awt.Dimension(1378, 766));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control hide and show.png"))); // NOI18N
        showbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showbtnMouseClicked(evt);
            }
        });
        getContentPane().add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        addbuyerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new buyer.png"))); // NOI18N
        addbuyerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addbuyerbtnComponentShown(evt);
            }
        });
        addbuyerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuyerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbuyerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        updatebuyerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update buyer.png"))); // NOI18N
        updatebuyerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updatebuyerbtnComponentShown(evt);
            }
        });
        updatebuyerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuyerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebuyerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        buydetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buyer Details.png"))); // NOI18N
        buydetbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buydetbtnComponentShown(evt);
            }
        });
        buydetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buydetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(buydetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        delbuybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete buyer.png"))); // NOI18N
        delbuybtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                delbuybtnComponentShown(evt);
            }
        });
        delbuybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbuybtnActionPerformed(evt);
            }
        });
        getContentPane().add(delbuybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        addprobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        addprobtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addprobtnComponentShown(evt);
            }
        });
        addprobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprobtnActionPerformed(evt);
            }
        });
        getContentPane().add(addprobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        updprobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update product.png"))); // NOI18N
        updprobtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updprobtnComponentShown(evt);
            }
        });
        updprobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updprobtnActionPerformed(evt);
            }
        });
        getContentPane().add(updprobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        prodetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details product.png"))); // NOI18N
        prodetbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                prodetbtnComponentShown(evt);
            }
        });
        prodetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(prodetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        delprobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete product.png"))); // NOI18N
        delprobtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                delprobtnComponentShown(evt);
            }
        });
        delprobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delprobtnActionPerformed(evt);
            }
        });
        getContentPane().add(delprobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        billbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing.png"))); // NOI18N
        billbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billbtnComponentShown(evt);
            }
        });
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });
        getContentPane().add(billbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnlogout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnlogoutComponentShown(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, -1));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Buyer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Buyer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buyer details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete buyer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Product");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Product");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Product details");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete product");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Billing");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Close ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 600, 430));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back 2.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
       int a = JOptionPane.showConfirmDialog(null, "Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           setVisible(false);
           new login().setVisible(true);
       }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_btncloseActionPerformed

    private void showbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showbtnMouseClicked
        if(z==0)
        {
            try{
            Thread.sleep(250);
            addbuyerbtn.setVisible(true);
            jLabel2.setVisible(true);
            }
            catch(Exception e)
            {}
        }
        else
        {
          addbuyerbtn.setVisible(false);
        updatebuyerbtn.setVisible(false);
        buydetbtn.setVisible(false);
        delbuybtn.setVisible(false);
        addprobtn.setVisible(false);
        updprobtn.setVisible(false);
        prodetbtn.setVisible(false);
        delprobtn.setVisible(false);
        billbtn.setVisible(false);
        btnlogout.setVisible(false);
        btnclose.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel8.setVisible(false);
         jLabel9.setVisible(false);
         jLabel10.setVisible(false);
         jLabel11.setVisible(false);
         jLabel12.setVisible(false);
         z=0;
        }
    }//GEN-LAST:event_showbtnMouseClicked

    private void addbuyerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addbuyerbtnComponentShown
        try{
            Thread.sleep(250);
            updatebuyerbtn.setVisible(true);
            jLabel3.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_addbuyerbtnComponentShown

    private void updatebuyerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updatebuyerbtnComponentShown
        try{
            Thread.sleep(250);
            buydetbtn.setVisible(true);
            jLabel4.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_updatebuyerbtnComponentShown

    private void buydetbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buydetbtnComponentShown
        try{
            Thread.sleep(250);
            delbuybtn.setVisible(true);
            jLabel5.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_buydetbtnComponentShown

    private void delbuybtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_delbuybtnComponentShown
        try{
            Thread.sleep(250);
            addprobtn.setVisible(true);
            jLabel6.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_delbuybtnComponentShown

    private void addprobtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addprobtnComponentShown
         try{
            Thread.sleep(250);
            updprobtn.setVisible(true);
            jLabel7.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_addprobtnComponentShown

    private void updprobtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updprobtnComponentShown
         try{
            Thread.sleep(250);
            prodetbtn.setVisible(true);
            jLabel8.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_updprobtnComponentShown

    private void prodetbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_prodetbtnComponentShown
         try{
            Thread.sleep(250);
            delprobtn.setVisible(true);
            jLabel9.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_prodetbtnComponentShown

    private void delprobtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_delprobtnComponentShown
         try{
            Thread.sleep(250);
            billbtn.setVisible(true);
            jLabel10.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_delprobtnComponentShown

    private void billbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billbtnComponentShown
         try{
            Thread.sleep(250);
            btnlogout.setVisible(true);
            jLabel11.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_billbtnComponentShown

    private void btnlogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnlogoutComponentShown
          try{
            Thread.sleep(250);
            btnclose.setVisible(true);
            jLabel12.setVisible(true);
            z=1;
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnlogoutComponentShown

    private void addbuyerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuyerbtnActionPerformed
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_addbuyerbtnActionPerformed

    private void updatebuyerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuyerbtnActionPerformed
        new updateBuyer().setVisible(true);
    }//GEN-LAST:event_updatebuyerbtnActionPerformed

    private void buydetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buydetbtnActionPerformed
        new buyersDetails().setVisible(true);
    }//GEN-LAST:event_buydetbtnActionPerformed

    private void delbuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbuybtnActionPerformed
        new deleteBuyer().setVisible(true);
    }//GEN-LAST:event_delbuybtnActionPerformed

    private void addprobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprobtnActionPerformed
        new newProduct().setVisible(true);
    }//GEN-LAST:event_addprobtnActionPerformed

    private void updprobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updprobtnActionPerformed
        new updateProduct().setVisible(true);
    }//GEN-LAST:event_updprobtnActionPerformed

    private void prodetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodetbtnActionPerformed
        new productDetails().setVisible(true);
    }//GEN-LAST:event_prodetbtnActionPerformed

    private void delprobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delprobtnActionPerformed
        new deleteProduct().setVisible(true);
    }//GEN-LAST:event_delprobtnActionPerformed

    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        new billing().setVisible(true);
    }//GEN-LAST:event_billbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbuyerbtn;
    private javax.swing.JButton addprobtn;
    private javax.swing.JButton billbtn;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton buydetbtn;
    private javax.swing.JButton delbuybtn;
    private javax.swing.JButton delprobtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton prodetbtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JButton updatebuyerbtn;
    private javax.swing.JButton updprobtn;
    // End of variables declaration//GEN-END:variables
}
